# Generated by Django 5.1.4 on 2025-01-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agentmvp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitor",
            name="private_ip",
        ),
    ]
