# Generated by Django 5.1.4 on 2025-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentmvp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchreport",
            name="sales_strategy",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
