# Generated by Django 5.1.4 on 2025-02-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentmvp", "0002_researchreport_sales_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchreport",
            name="sales_strategy",
            field=models.JSONField(),
        ),
    ]
