# Generated by Django 5.1.4 on 2025-02-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agentmvp", "0003_alter_researchreport_sales_strategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorConversationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_phase",
                    models.CharField(default="initial_greetings", max_length=50),
                ),
                ("conversation_history", models.JSONField(default=list)),
                ("context", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_states",
                        to="agentmvp.agent",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversation_states",
                        to="agentmvp.visitor",
                    ),
                ),
            ],
            options={
                "unique_together": {("visitor", "agent")},
            },
        ),
    ]
